### PR TITLE
fix: infection should be a dev dependency

### PR DESCRIPTION
**Pull request by odinuv**

### CODE REVIEW

**Comment by odinuv** [comment]
na CI mi to failuje na `{"errorMessage":"\"value\" must be an object","errorCode":422,"requestId":"offline_awsRequestId_ck1khv2rp005k01rvfkb60ks2"}`

pri curl -X POST http://internal-api:3000/index -H 'Content-Type: application/json'

lokalne to jede, image je stejnej

**Comment by MiroCillik** [comment]
Ok, mrknem na to. Inak to vyzera OK.

**Comment by odinuv** [comment]
lowprio

**Comment by MiroCillik** [comment]
Tvl, tak to som z toho 🦌 ...
Updatol som ten image v dockerhube rucne a porovnal ho s tym v CI a ma rovnaky digest.

Tu to pouzivam uplne rovnako, akurat ten curl volam z phpka 
https://github.com/keboola/job-queue-api/blob/master/tests/AppFunctionalTest.php#L26

Builds:
https://travis-ci.com/keboola/job-queue-api/builds

**Comment by odinuv** [comment]
no vsak jsem to psal, ze to ma stejnej image :)
tak jestli se to vola spravne, tak se muzem pohrabat v tom workeru co je tam teda jinak - i kdyz moc nechapu co, kdyz je to jeden command v dockeru bez parameteru

**Comment by MiroCillik** [comment]
Mne to pripada, akoby si ten Serverless myslel, ze volas inu url cestu a nie `/index`

**Comment by MiroCillik** [comment]
Jedine co ma napada, ze by to nejak divne sparsovalo ten curl command? Tvl, to bude nejaka picovina..

**Comment by odinuv** [comment]
@MiroCillik tak to funguje, rekl bych, ze to zpusobilo `apt-get upgrade` na tom workeru :/

**Comment by MiroCillik** [comment]
Super

**Pull request merged**
